name: CD Node

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    # Runs a single command using the runners shell
    - name: Fetch deps
      working-directory: ./client
      run: npm i
      
    - name: Build frontend
      working-directory: ./client
      run: |
        NODE_ENV=prod npm run build
        rm -r /var/www/html/soli/img/
        mv -v ./dist/* ../server/app/
        echo "done :)"

    - name: Prepare backend
      working-directory: ./server
      run: |
        [ ! -d ".venv" ] && python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
        screen -X -S soli quit
        screen -dmS soli bash -c 'FLASK_ENV=development flask run --host=0.0.0.0 --port 5555'
        
    - name: Purge cache
      uses: jakejarvis/cloudflare-purge-action@master
      env:
        # Zone is required by both authentication methods
        CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
        PURGE_URLS: '["https://lambda.wtf/soli/index.html", "https://lambda.wtf/soli/app.js", "https://lambda.wtf/soli/favicon.ico"]'
